### ISSUE TITLE
Minimal working example not working

### ISSUE THREAD

**Issue by IronTessaro** [kartelj/rils-rols#5]
While running the minimal working example I got the following error during the testing phase, only for the RILSROLSEnsembleRegressor:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-13-699266cb06a0>](https://localhost:8080/#) in <cell line: 3>()
      1 # applies the model to a list of input vectors, also well-known predict method
      2 X_test = [[4, 4], [3, 3]]
----> 3 y_test = regressor.predict(X_test)
      4 print(y_test)

8 frames
[/content/rils-rols/rils_rols/node.py](https://localhost:8080/#) in evaluate_inner(self, X, a, b)
    206             raise Exception("Variable with index " +
    207                             str(self.index)+" does not exist.")
--> 208         return X[:, self.index]
    209 
    210     def __str__(self):

TypeError: list indices must be integers or slices, not tuple

**Comment by kartelj** [comment]
Version 1.2 is pure python, while 1.4+ (current is 1.5.10) are C++ wrapped as a python module. 
I recommend using only the latter, at this moment version 1.5.10 is relatively stable. 
In order to give complete answer to this question, two colab notebooks are created:

1) https://colab.research.google.com/drive/1BujSPRKDpIOUXFFxedAk4FgXYv4dBTKs?usp=sharing (this one for the version 1.2 with instructions on how to use it here: https://pypi.org/project/rils-rols/1.2)

2) https://colab.research.google.com/drive/1U8I92VTQao9UA9ErBK3VX9AbpIX1LLIv#scrollTo=IdTS8UfmPVVo (this one is for the new and default version 1.5.10), while the instructions are linked from the pypi repository" https://pypi.org/project/rils-rols/1.5.10/

**Comment by IronTessaro** [comment]
Thank you again! Both codes worked well for me.
